import { Injectable } from '@angular/core';
import { addDoc, query, getDocs, where, deleteDoc, doc, DocumentReference } from 'firebase/firestore';
import { Location } from '../models/Location';
import { Firestore, collection } from '@angular/fire/firestore';


@Injectable({
  providedIn: 'root'
})
export class LocationService {

  constructor(private firestore: Firestore) { }

  async save(location: Location) {
    const docRef = await addDoc(collection(this.firestore, 'locations'), location);
    return docRef;
  }

  async getAll() {
    const docsRef = await getDocs(query(collection(this.firestore, 'locations')));
    return docsRef.docs.map(doc => doc.data());
  }

  async getByEmail(email: string) {
    const q = query(collection(this.firestore, 'locations'), where("owner", "==", email));
    const docsRef = await getDocs(q);
    return docsRef.docs.map(doc => doc.data());
  }

  async get(email: string, name: string) {
    const q = query(collection(this.firestore, 'locations'), where("owner", "==", email), where("name", "==", name));
    const docsRef = await getDocs(q);
    return docsRef.docs.at(0)?.data();
  }

  async delete(email: string, name: string) {
    const q = query(collection(this.firestore, 'locations'), where("owner", "==", email), where("name", "==", name));
    const docsRef = await getDocs(q);
    return deleteDoc(docsRef.docs.at(0)?.ref as DocumentReference);
  }

  static CITY_LIST = [
    "Budapest",
    "Debrecen",
    "Székesfehérvár",
    "Pécs",
    "Győr",
    "Szeged",
    "Nyíregyháza",
    "Kecskemét",
    "Szombathely",
    "Miskolc",
    "Veszprém",
    "Kaposvár",
    "Gödöllő",
    "Sopron",
    "Érd",
    "Szolnok",
    "Tatabánya",
    "Zalaegerszeg",
    "Békéscsaba",
    "Eger",
    "Nagykanizsa",
    "Dunakeszi",
    "Hódmezővásárhely",
    "Dunaújváros",
    "Szigetszentmiklós",
    "Cegléd",
    "Mosonmagyaróvár",
    "Vác",
    "Baja",
    "Salgótarján",
    "Ózd",
    "Szekszárd",
    "Budaörs",
    "Pápa",
    "Esztergom",
    "Szentendre",
    "Gyöngyös",
    "Ajka",
    "Gyál",
    "Siófok",
    "Kazincbarcika",
    "Tata",
    "Dunaharaszti",
    "Göd",
    "Komló",
    "Vecsés",
    "Fót",
    "Veresegyház",
    "Hatvan",
    "Gyömrő",
    "Komárom",
    "Várpalota",
    "Monor",
    "Pomáz",
    "Szigethalom",
    "Oroszlány",
    "Keszthely",
    "Százhalombatta",
    "Békés",
    "Pécel",
    "Mohács",
    "Dombóvár",
    "Mezőkövesd",
    "Tiszaújváros",
    "Budakeszi",
    "Mátészalka",
    "Biatorbágy",
    "Sárvár",
    "Kisvárda",
    "Törökbálint",
    "Kalocsa",
    "Pilisvörösvár",
    "Tapolca",
    "Balassagyarmat",
    "Hajdúsámson",
    "Kerepestarcsa",
    "Albertirsa",
    "Gárdony",
    "Sátoraljaújhely",
    "Hajdúhadház",
    "Balatonfüred",
    "Üllő",
    "Maglód",
    "Bonyhád",
    "Budakalász",
    "Nagykáta",
    "Halásztelek",
    "Pilis",
    "Kőszeg",
    "Isaszeg",
    "Diósd",
    "Dorog",
    "Nyírbátor",
    "Tököl",
    "Bátonyterenye",
    "Sajószentpéter",
    "Bicske",
    "Ráckeve",
    "Solymár",
    "Tolna",
    "Tárnok",
    "Körmend",
    "Csömör",
    "Balatonalmádi",
    "Celldömölk",
    "Szigetvár",
    "Erdőkertes",
    "Edelény",
    "Dunavarsány",
    "Nagykovácsi",
    "Siklós",
    "Piliscsaba",
    "Páty",
    "Szerencs",
    "Sándorfalva",
    "Üröm",
    "Őrbottyán",
    "Győrújbarát",
    "Mogyoród",
    "Tura",
    "Velence",
    "Nyergesújfalu",
    "Füzesabony",
    "Fehérgyarmat",
    "Taksony",
    "Kozármisleny",
    "Zirc",
    "Felsőzsolca",
    "Putnok",
    "Szada",
    "Nagytarcsa",
    "Téglás",
    "Tahitófalu",
    "Tápiószecső",
    "Encs",
    "Aszód",
    "Szentlőrinc",
    "Kartal",
    "Nagyecsed",
    "Martonvásár",
    "Tápiószele",
    "Délegyháza",
    "Zsámbék",
    "Martfů",
    "Szikszó",
    "Lőrinci",
    "Balatonboglár",
    "Tát",
    "Mikepércs",
    "Nagymaros",
    "Nyékládháza",
    "Rákóczifalva",
    "Lábatlan",
    "Sződliget",
    "Inárcs",
    "Szabadbattyán",
    "Onga",
    "Harkány",
    "Nyúl",
    "Balatonfůzfő",
    "Hévíz",
    "Telki",
    "Kótaj",
    "Szirmabesenyő",
    "Mályi",
    "Pilisborosjenő",
    "Pilisszentiván",
    "Ceglédbercel",
    "Tokod",
    "Hernád",
    "Tab",
    "Mende",
    "Ecser",
    "Leányfalu",
    "Gyenesdiás",
    "Győrzámoly",
    "Bük",
    "Záhony",
    "Felsőpakony",
    "Bag",
    "Bóly",
    "Nyírpazony",
    "Csobánka",
    "Vértesszőlős",
    "Sződ",
    "Cserszegtomaj",
    "Herend",
    "Hévizgyörk",
    "Gönyů",
    "Tuzsér",
    "Abda",
    "Kakucs",
    "Csolnok",
    "Harka",
    "Baj",
    "Sajólád",
    "Sásd",
    "Herceghalom",
    "Pócsmegyer",
    "Sárisáp",
    "Szigetcsép",
    "Múcsony",
    "Forró",
    "Pilisszántó",
    "Nagycenk",
    "Andornaktálya",
    "Péteri",
    "Úrhida",
    "Verőcemaros",
    "Szigetszentmárton",
    "Sajóbábony",
    "Kisbocskaykert",
    "Győrújfalu",
  ]
}
